config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :bands
  resources :organizers
  resources :genres
  resources :events
  root to: 'events#index'
  get 'visitors/all'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
end

app/models/organizer.rb
class Organizer < ActiveRecord::Base
  has_and_belongs_to_many :events
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_action :set_organizer, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /organizers
  # GET /organizers.json
  def index
    @organizers = Organizer.all
  end

  # GET /organizers/1
  # GET /organizers/1.json
  def show
  end

  # GET /organizers/new
  def new
    @organizer = Organizer.new
  end

  # GET /organizers/1/edit
  def edit
  end

  # POST /organizers
  # POST /organizers.json
  def create
    @organizer = Organizer.new(organizer_params)

    respond_to do |format|
      if @organizer.save
        format.html { redirect_to @organizer, notice: 'Organizer was successfully created.' }
        format.json { render :show, status: :created, location: @organizer }
      else
        format.html { render :new }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizers/1
  # PATCH/PUT /organizers/1.json
  def update
    respond_to do |format|
      if @organizer.update(organizer_params)
        format.html { redirect_to @organizer, notice: 'Organizer was successfully updated.' }
        format.json { render :show, status: :ok, location: @organizer }
      else
        format.html { render :edit }
        format.json { render json: @organizer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizers/1
  # DELETE /organizers/1.json
  def destroy
    @organizer.destroy
    respond_to do |format|
      format.html { redirect_to organizers_url, notice: 'Organizer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organizer
      @organizer = Organizer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organizer_params
      params.require(:organizer).permit(:name)
    end
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/views/organizers/_form.html.erb
<%= simple_form_for(@organizer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organizers/edit.html.erb
<h1>Editing Organizer</h1>

<%= render 'form' %>

<%= link_to 'Show', @organizer %> |
<%= link_to 'Back', organizers_path %>

app/views/organizers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizers.each do |organizer| %>
      <tr>
        <td><%= organizer.name %></td>
        <td><%= link_to 'Show', organizer %></td>
        <td><%= link_to 'Edit', edit_organizer_path(organizer) %></td>
        <td><%= link_to 'Destroy', organizer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organizer', new_organizer_path %>

app/views/organizers/new.html.erb
<h1>New Organizer</h1>

<%= render 'form' %>

<%= link_to 'Back', organizers_path %>

app/views/organizers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organizer.name %>
</p>

<%= link_to 'Edit', edit_organizer_path(@organizer) %> |
<%= link_to 'Back', organizers_path %>