config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :bands
  resources :organizers
  resources :genres
  resources :events
  root to: 'events#index'
  get 'visitors/all'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :event_name,:start_date,:end_date, presence: true

  has_and_belongs_to_many :genres
  has_and_belongs_to_many :organizers
  has_and_belongs_to_many :bands
  belongs_to :venue

  def to_time
    self.start_date.strftime("%l:%M %P")
  end
  def to_date
    self.start_date.strftime("%e,  %Y")
  end
  def to_month
    self.start_date.strftime("%B,  %Y")
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  #before_action :authenticate_user!, except: [:index, :show, :search]
  # check diff bet before_action & before_filter later
  # GET /events
  # GET /events.json
  def index
    @events = Event.all.order('created_at DESC')
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :event_type, :age_limit, :start_date, :end_date, :dresscode, :price, :user_id, band_ids:[], genre_ids:[], organizer_ids:[])
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>        
<%# f.error_notification %>
<% if @event.errors.any? %>
<fieldset>
  <legend>
<h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from creation</h2></legend>
    <ul>
      <% @event.errors.full_messages.each do |msg|  %>
        <li><%= msg %></li>
      <% end %>
    </ul>
 </fieldset>   
  <% end %>
  <section class="row">
      <%# Event Form Elements %>
      <fieldset>
        <legend>Choose Name, Type, Age Limit</legend>
        <%# div class="form-inputs" %>
          <div class="small-4 columns"> 
          <%= f.input :event_name, error: 'Event name is mandatory' %>
          <small><%= f.hint 'Artist @ Venue' %></small>
          </div>
          <div class="small-4 columns"> 
          <%= f.label "Type" %>
          <%= f.select :event_type,
          ["Nightclub","Festival", "Special Event"]%>
          </div>
          <div class="small-4 columns">
          <%= f.label "Age Limit" %> 
          <%= f.select :age_limit,
          ["21+","18+","16+","All Ages"]%>
          </div>

          </fieldset>

      <fieldset>
        <legend>Choose Venue, Date & Time</legend>
        <%# Venue Form Elements %>
            <div class="small-4 columns panel radius">
              <%= f.label "Choose Your Venue or Add One"%><br />
              <%= f.collection_select :venue_id, Venue.all, :id, :name, prompt: true %>
              <%= link_to 'Add Venue', new_venue_path %>
            </div>
        <div class="small-4 columns">
          <%= f.label :start_date %>
          <%= f.text_field :start_date %>
          <%= f.input :start_time %>
        </div>
        <div class="small-4 columns">
          <%= f.label :end_date %>
          <%= f.text_field :end_date %>
          <%= f.input :end_time %>
        </div>
      </fieldset>

      <%# Band form Elements %>
      <fieldset>
        <legend>Choose Artists</legend>
        <%= f.collection_check_boxes :band_ids, Band.all, :id, :name do |b| %>
          <div class=" small-4 columns collection-check-box"> 
            <%= b.check_box %>
            <%= b.label %>
          </div> 
        <% end %>
      </fieldset>
    

      <fieldset>
        <legend>Genre</legend>      
        <%# Genre Form Elements %>
        <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name do |b| %>
          <div class=" small-4 columns collection-check-box">
                  <%= b.check_box %>
                  <%= b.label %>
          </div>
        <% end %>
      </fieldset>     
      <fieldset>    
      <%# Organizer Form Elements %>
        <legend>Choose Organizers</legend>
        <%= f.collection_check_boxes :organizer_ids, Organizer.all, :id, :name do |b| %>
          <div class="collection-check-box">
              <%= b.check_box %>
              <%= b.label %>
          </div>
        <% end %>
      </fieldset>       

    </section>
        <div class="form-actions">
          <%= f.button :submit, class:"radius"%>
        </div>

    <% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>
  
<div class="row">
  <section class="small-12 columns ">
    <%#
      <article class="event">
      <div class="event-date">
        <p class="event-month">January</p>
        <p class="event-day">26</p>
    </div>
      <div class="event-desc">
        <h4 class="event-desc-header">Day in the Life of Foundation for Apps</h4>
        <p class="event-desc-detail"><span class="event-desc-time"></span>BDConf - Altlanta</p>
        <a href="#" class="rsvp button">RSVP &amp; Details</a>
      </div>
    </article><hr>%>
    <% @events.each do |event| %>
      <article class="event">
        <div class="event-date">
          <p class="event-month"><%= event.start_date.try(:strftime,'%B') %></p>
          <p class="event-day"><%= event.start_date.try(:strftime,'%e') %></p>
        </div>
        <div class="event-desc">
          <h4 class="event-desc-header"><%= event.event_name %></h4>
          <% if event.venue %>
          <p class="event-desc-detail"><%= event.venue.name %></p>
          <% end %>
          <p class="event-desc-detail"><%= event.bands.map(&:name).sort.join(", ") %></p>
          <p class="event-desc-detail"><%= event.genres.map(&:name).sort.join(", ") %></p>
          <p class="event-desc-detail"><%= event.organizers.map(&:name).sort.join(", ") %></p>
          <small><%= link_to 'Show', event %></small>
          <small><%= link_to 'Edit', edit_event_path(event) %></small>
          <small><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></small>
        </div>
        </article><hr>
    <% end %>
    <%# link_to 'Add Events', new_event_path, class:"fi-plus small" %>
  </section>
  <div class="row">
  <aside class="small-12 columns">
      <div class="button-group">
        <%# link_to 'Add Event', new_event_path,class:"fi-plus small" %> 
        <%# link_to 'Add Genre', new_genre_path,class:"fi-plus small" %> 
        <%# link_to 'Add Organizer', new_organizer_path,class:"fi-plus small" %> 
        <%# link_to 'Add Band', new_band_path,class:"fi-plus small"%>
      </div>
      
    </aside>
    </div>

</div>

app/views/events/new.html.erb
 <%# link_to ' Back to All Events', events_path,class:"fi-home"%>
 <%= render 'form' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.event_name %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>