config/routes.rb
Rails.application.routes.draw do
  resources :venues
  resources :bands
  resources :organizers
  resources :genres
  resources :events
  root to: 'events#index'
  get 'visitors/all'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
end

app/views/layouts/_footer.html.erb
<div class="stickyFooter" id="mobileFooter">
  <div class="footerLinksWrapper">
    
    <div class="row centerHorizListWrapper">
      <ul class="centerHorizList" id="footerMiniLinks">
        <li><%= link_to 'Submit New Event', new_event_path  %></li>
        <li>|</li>
        <li><%= link_to 'Terms of Use', page_path('terms') %></li>
        <li>|</li>
        <li><%= link_to 'Privacy', page_path('privacy') %></li>
        <li>|</li>
        <li> &copy; Edmbooth, 2016 </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<%# Right Nav Sections  %>
<% if user_signed_in? %>
  <li><%= link_to 'Account', edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Register', new_user_registration_path %></li>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Edmbooth', root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon">
      <a href="#"><span></span></a>
    </li>
  </ul>
  <div class="top-bar-section">
    
      <ul class="right">
          <%= render 'layouts/nav_links_for_auth' %>
      </ul>
      
      <ul class="left">
        <%= render 'layouts/navigation_links' %>
      </ul>
      
      <% if user_signed_in? %>
        <p class="right" >Hello, <%= current_user.username.capitalize %></p>
      <% end %>  
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# Left Nav Section %>
<%# add navigation links to this file %>

<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', page_path('contact') %></li>
<li><%= link_to 'Events', events_path%></li>
<li><%= link_to 'Venues', venues_path%></li>
<li><%= link_to 'Genres', genres_path%></li>
<li><%= link_to 'Organizers', organizers_path%></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Samaritan" %>
    </title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Edmbooth" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="row">
      <%= render 'layouts/navigation' %>
    </header>
    <div class="row">
      <main role="main">
         <%= render 'layouts/messages' %>
         <%= yield %>
      </main>
    </div>
    <footer class="row">
      <div class="large-12 columns">
        <%= render 'layouts/footer' %>
      </div>
    </footer>
  </body>
</html>